// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CometUserAPI.Entities;

[Table("tbl_employee")]
public partial class TblEmployee
{
    [Key]
    [Column("code")]
    public int Code { get; set; }

    [Column("name")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("email")]
    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Column("designation")]
    [StringLength(50)]
    [Unicode(false)]
    public string Designation { get; set; }
}