// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CometUserAPI.Entities;

[Table("tbl_otpManager")]
public partial class TblOtpManager
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("username")]
    [StringLength(50)]
    [Unicode(false)]
    public string Username { get; set; }

    [Required]
    [Column("otptext")]
    [StringLength(10)]
    [Unicode(false)]
    public string Otptext { get; set; }

    [Column("otptype")]
    [StringLength(20)]
    [Unicode(false)]
    public string Otptype { get; set; }

    [Column("expiration", TypeName = "datetime")]
    public DateTime Expiration { get; set; }

    [Column("createddate", TypeName = "datetime")]
    public DateTime? Createddate { get; set; }
}