// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CometUserAPI.Entities;

[PrimaryKey("RoleId", "MenuId")]
[Table("tbl_permission")]
public partial class TblPermission
{
    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string RoleId { get; set; }

    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string MenuId { get; set; }
}