// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CometUserAPI.Entities;

[Table("tbl_productimage")]
public partial class TblProductimage
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("productcode")]
    [StringLength(50)]
    [Unicode(false)]
    public string Productcode { get; set; }

    [Column("productimage", TypeName = "image")]
    public byte[] Productimage { get; set; }
}