// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CometUserAPI.Entities;

[Table("tbl_product_image")]
public partial class TblProductImage
{
    [Column("productCode")]
    [StringLength(50)]
    [Unicode(false)]
    public string ProductCode { get; set; }

    [Column("productImage", TypeName = "image")]
    public byte[] ProductImage { get; set; }

    [Key]
    [Column("id")]
    public int Id { get; set; }
}