// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CometUserAPI.Entities;

[Table("tbl_refreshtoken")]
public partial class TblRefreshtoken
{
    [Key]
    [Column("userid")]
    [StringLength(50)]
    [Unicode(false)]
    public string Userid { get; set; }

    [Column("tokenid")]
    [StringLength(50)]
    [Unicode(false)]
    public string Tokenid { get; set; }

    [Column("refreshtoken")]
    [Unicode(false)]
    public string Refreshtoken { get; set; }
}