// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CometUserAPI.Entities;

[Table("tbl_role")]
public partial class TblRole
{
    [Key]
    [Column("code")]
    [StringLength(50)]
    public string Code { get; set; }

    [Required]
    [Column("name")]
    [StringLength(200)]
    public string Name { get; set; }

    [Column("status")]
    public bool? Status { get; set; }
}