// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CometUserAPI.Entities;

[Table("tbl_tempuser")]
public partial class TblTempuser
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("code")]
    [StringLength(50)]
    [Unicode(false)]
    public string Code { get; set; }

    [Required]
    [Column("name")]
    [StringLength(250)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("email")]
    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [Column("phone")]
    [StringLength(20)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Column("password")]
    [StringLength(50)]
    [Unicode(false)]
    public string Password { get; set; }
}